import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Renzo Damian - React Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="main">
				<div className="container">
					<div className="flex justify-center items-center h-screen w-screen flex-col gap-4 px-6">
						<h1 className=" text-4xl md:text-6xl md:w-[600px] text-center">
							<span className="flex justify-center items-center gap-2 md:gap-3">
								Hola{' '}
								<img
									className=" h-[40px] md:h-[60px] md:w-[60px]"
									src="/imgs/waving_hand.png"
									height={40}
									width={40}
									alt="Hola"
								/>
							</span>
							Estoy creando un portfolio{' '}
							<span className="font-semibold">Next Gen</span>.
						</h1>
						<p>Vuelva más tarde :)</p>
					</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
